#' Mediaplots: Quickly analyze mediascraper-output visually
#'
#' @param datacon Either a dataframe or a sql-connection-object that was generated by the mediascraper-function
#' @param dbname The name of the sql-database. Only necessary if you provided a connection-object in datacon. Default: NULL
#' @param plots Provides a summary of the scraped data in the form of basic plots if TRUE. Plots show: Number of articles per outlet scraped and mean-length of title/lead/body of the articles that where scraped. Default: TRUE
#' @param searchterm Regex-expression, string, word you want to search for. Prints a plot with the number of found appearances per media-outlet. Default: NULL
#' @param searchtarget Destination in which you want to search for the search term. Can either be "title", "lead" or "body". Default: "title"
#'
#' @return ggplots
#' @export
#'
#' @examples
#' scrapingresults = data.frame(title = rep("Test", 3), lead = rep("Test", 3),
#' body = rep("Test", 3), outlet = c("Watson", "20 Minuten", "SRF"))
#' mediaplots(scrapingresults, plots = TRUE)
#' mediaplots(scrapingresults, plots = TRUE, searchterm = "Test")
mediaplots = function(datacon, dbname = NULL, plots = TRUE, searchterm = NULL, searchtarget = "title"){
  suppressMessages(require(ggplot2))
  suppressMessages(require(dplyr))
  suppressMessages(require(stringr))


  # Checking inputs
  # Checking if provided element is either a data.frame or an sql-connection object
  if ("SQLiteConnection" %in% class(datacon)){
    if(!is.null(dbname)){
      suppressMessages(require(DBI))
      results_df = dbReadTable(datacon, dbname)}
    else{
      stop("Error: You must provide the name of the database by specifying the parameter dbname")}
  }else if ("data.frame" %in% class(datacon)){
    results_df = datacon
  }else{
    stop("Error: You must either pass a data.frame or a connection-object and a dbname generated by the mediascraper-function")
  }

  # Checking if dataframe was produced by mediascraper-function
  columns = c("body", "lead", "outlet", "title")
  if (any(columns %in% ls(results_df)==FALSE)) {
    stop("Error: The object you passed was not generated by the mediascraper-function. Object must contain title-, lead-, body- and outlet-columns")
  }


  # Setting colors for the different outlets
  colors <- c("Watson" = "#F40F96", "20 Minuten" = "#0D2880", "SRF" = "#AF001D", "Tagesanzeiger" = "#000000")

  # Summary plots
  if (plots == TRUE){


    nrart <- results_df |> group_by(outlet) |>
      summarize(n = n()) |> ggplot(aes(x = outlet, y = n, color = outlet, fill =
                                         outlet)) +
      geom_col(width = 0.5, show.legend = F) +
      xlab("Outlet") + ylab("Number of Articles")  +
      ggtitle("Number of Scrapped Articles per Outlet") + theme_bw() +
      scale_fill_manual(values = colors) + scale_color_manual(values = colors)
    print(nrart)

    # Length of title
    lete <- results_df |> group_by(outlet) |>
      summarize(titlelength = mean(nchar(title), na.rm = T)) |> ggplot(aes(x = outlet,
                                                                           y = titlelength,
                                                                           color = outlet,
                                                                           fill = outlet)) +
      geom_col(width = 0.5, show.legend = F) + xlab("Outlet") +
      ylab("Number of Characters")  + ggtitle("Mean Length of Article-Title") +
      theme_bw() + scale_fill_manual(values = colors) + scale_color_manual(values = colors)
    print(lete)

    # Length of lead
    lele <- results_df |> group_by(outlet) |>
      summarize(leadlength = mean(nchar(lead), na.rm = T)) |> ggplot(aes(x = outlet,
                                                                         y = leadlength,
                                                                         color = outlet,
                                                                         fill = outlet)) +
      geom_col(width = 0.5, show.legend = F) + xlab("Outlet") +
      ylab("Number of Characters")  +
      ggtitle("Mean Length of Article-Lead") + theme_bw() + scale_fill_manual(values = colors)  + scale_color_manual(values = colors)
    print(lele)

    # Length of body
    lebo <- results_df |> group_by(outlet) |>
      summarize(bodylength = mean(nchar(body), na.rm = T)) |>
      filter(!outlet == "SRF") |> filter(!outlet == "Tagesanzeiger") |> ggplot(aes(x = outlet,
                                                                                   y = bodylength,
                                                                                   color = outlet,
                                                                                   fill = outlet)) +
      geom_col(width = 0.5, show.legend = F) + xlab("Outlet") +
      ylab("Number of Characters")  + ggtitle("Mean Length of Article-Body") +
      theme_bw() + scale_fill_manual(values = colors)  + scale_color_manual(values = colors)
    print(lebo)
  }





  # Search for appearances of a specific word in title, lead or body of the articles.
  if (!is.null(searchterm) && searchtarget == "title"){
    wordo <- results_df  |>
      mutate(word_count = str_count(title, searchterm)) |> group_by(outlet) |>
      summarise(
        word_count = sum(word_count)
      ) |> ggplot(aes(x = outlet, y = word_count, color = outlet, fill = outlet)) +
      geom_col(width = 0.5, show.legend = F) + xlab("Outlet") +
      ylab("Number of Appearances")  +
      ggtitle("Number of Appearances of Word Specified") + theme_bw() + scale_fill_manual(values = colors)  + scale_color_manual(values = colors)
    print(wordo)}

  else if (!is.null(searchterm) && searchtarget == "lead"){
    wordo <- results_df  |>
      mutate(word_count = str_count(lead, searchterm)) |> group_by(outlet) |>
      summarise(
        word_count = sum(word_count)
      ) |> ggplot(aes(x = outlet, y = word_count, color = outlet, fill = outlet)) +
      geom_col(width = 0.5, show.legend = F) + xlab("Outlet") +
      ylab("Number of Appearances")  +
      ggtitle("Number of Appearances of Word Specified") + theme_bw() + scale_fill_manual(values = colors)  + scale_color_manual(values = colors)
    print(wordo)}

  else if (!is.null(searchterm) && searchtarget == "body"){
    wordo <- results_df  |>
      mutate(word_count = str_count(body, searchterm)) |> group_by(outlet) |>
      summarise(
        word_count = sum(word_count)
      ) |> ggplot(aes(x = outlet, y = word_count, color = outlet, fill = outlet)) +
      geom_col(width = 0.5, show.legend = F) + xlab("Outlet") +
      ylab("Number of Appearances")  +
      ggtitle("Number of Appearances of Word Specified") + theme_bw() + scale_fill_manual(values = colors)  + scale_color_manual(values = colors)
    print(wordo)}

}
